.editorconfig, .eslintrc.js, .gitignore, commitlint.config.js, package-lock.json, package.json
- generic .gitignore
- generic .editorconfig
- markdown linter (eslint)
- lint commit message 
- auto-fixing of format errors of `.md` files upon git stage
=> chore: basic environment setup

docs/_posts/topics.md
First Version of possible Topics
=> Docs: Topic Collection

docs/index.markdown
added my name to extension topic (for testing if setup works)
=> docs: added name to extension topic

README.md
=> docs: hint that we're using gfm

README.md
=> docs(setup): hint for PR draft, jekyll livereload flag

docs/index.markdown, docs/mvc/baseController.markdown, docs/mvc/bindingMode.markdown, docs/mvc/dataBinding.markdown, docs/mvc/index.md, docs/nc/index.md, docs/nc/modelNaming.markdown, docs/nc/namespaces.markdown
Hi all,
I would like to contribute. 
Thanks and best regards,
Adrian
=> Added some points about MVC, Data Binding and Naming Conventions

docs/index.markdown
=> docs: topic assignment

docs/Gemfile.lock, docs/_includes/toc_landing_page.html, docs/_layouts/home.html, docs/_sass/custom/custom.scss, docs/about.markdown, docs/index.markdown, docs/topic_collection.markdown
- added landing page with Table of Contents
-  Table of Content are at the bottom of the landing page and all subpages are extended
- Using customized home layout with similar code to Standard Navigation
- Topic Collection is now a extra page
- Topic Collection and About Page is now at the bottom of the Navigation
=> docs(landing-page): added landing-page with toc

docs/_config.yml, docs/i18n/advancedFeatures.markdown, docs/i18n/index.md, docs/i18n/usage.markdown
- change Markdown Processor to kramdown to use [IAL](https://kramdown.gettalong.org/syntax.html#block-ials)
- Fix Bad / Good Example Template
- Fix Captions of Images
=> Change markdown procesor

docs/topic_collection.markdown
This PR adds my github-username to the topics where I want to contribute
=> Update Topic Collection

docs/i18n/advancedFeatures.markdown
first example of a live code sample with CodeSandbox.io
Basically, all code is stored in a repository, independent of CodeSandbox. As an example, I first created one under my name, and later one should be created under DSAG.
CodeSandbox serves as an ad hoc runtime environment with which pull requests can also be made directly in branches.
Independently of this, the UI5 sample app can of course also be executed and changed locally.
The main branch can be used as a basis.
All other examples can be created in branches.
As an example, I have created an example for i18n.
Here I have embedded a CodeSandbox.
The embedding must point directly to the branch of the repository.
So as an example, here in this PR shows the embedding to:
_**https://codesandbox.io/embed/github/marianfoo/codesandbox-ui5-b …
=> feat: Include live code sample i18n

README.md, contributing.md
- Improving the general overview of the readme and the table of contents
- Addition of the Contribution Guidelines in preparation for the Contributor License Agreement (CLA) assistant
=> docs: Improvements readme

.github/workflows/cla.yml
this github action checks if a contributor aggread to the contributing guidelines, aggrement is stored in repository
https://github.com/marketplace/actions/cla-assistant-lite
waiting for merge of contributing document #62
=> ci(cla): github action cla assistant

.github/workflows/cla.yml, docs/i18n/index.md
In this PR, the list is created with all contributors who have signed the CLA.
=> CLA Assistant: change branch for signatures

.devcontainer/devcontainer.json
I should have added it initially 😎
https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
=> chore: add gitlens to the dev container config

docs/testing/index.md
This tag added to the metadata will add a button on den overview page to the testing sample app in the other repository like already used in the i18n app https://1dsag.github.io/UI5-Best-Practice/i18n/
=> feat(testing): add button to sample app

.gitignore, package-lock.json, package.json, tsconfig.json
- Add Typescript for future scripts
=> Add Typescript for Linting

contributing.md, package.json
- add section about how to test markdown and general linting
=> Improve contributing Docs 

.github/workflows/generate_pdf.yml
From Issue #113 
Action can´t commit automatically on main branch
Workflow will be:
1. Create Branch From Main
2. Trigger 'pdf' action on new branch
3. Merge Branch to Main
Do this on good new content
=> Trigger GitHub Action 'Create PDF' manually 

docs/sample-apps/index.md
=> Add a sample apps overview page

docs/error-handling/bestpractices.md
Heyo 👋
was skimming through a bit and found this (possibly) copy/paste error(?). Anyway it seemed a bit out of place. 😅
BR,
Marco
=> fix(error-handling): removed duplicate sections

docs/i18n/advancedFeatures.md, docs/i18n/index.md, docs/i18n/usage.md
new section in i18n for supportedLocale and fallbackLocale since version 1.77
=> docs(i18n): add supportedLocale and fallbackLocale
